### PR TITLE
Shortened flow to connect to known networks

### PR DESCRIPTION
**Pull request by mperazam05**
# Overview
Fixes a bug that was causing us to try to set the password to `null` on every reconnect.

## Changes made
- Formatted the code.
- If when connecting to a Wi-Fi network the password is `null`, we check if it is the current or known network to reconnect.
- Removed unused code.

### CODE REVIEW

**Review by JacobStarfish — APPROVED** [review]
🚀

**Comment by bjdose** [comment]
I'm having this error when trying to connect to a network with the SSID: "null"

image

And the scanner says that the password is incorrect, but it's correct.

image

image

**Comment by mperazam05** [comment]
> I'm having this error when trying to connect to a network with the SSID: "null"

Is it like this in prod? Or does it work as expected there? @bjdose

**Comment by bjdose** [comment]
I connected the scanner to my phone hotspot but each time I try to connect it again (I switched to my normal network previously) the password input popups and request the password, but that network is a known network, right? Why is it asking for the pass again? Is this the expected behavior?

image

image

**Comment by bjdose** [comment]
> > I'm having this error when trying to connect to a network with the SSID: "null"
> 
> Is it like this in prod? Or does it work as expected there? @bjdose

On production, the connection is working

image

**Comment by mperazam05** [comment]
> I connected the scanner to my phone hotspot but each time I try to connect it again (I switched to my normal network previously) the password input popups and request the password, but that network is a known network, right? Why is it asking for the pass again? Is this the expected behavior?

Is it like this in prod? @bjdose

**Comment by bjdose** [comment]
> > I connected the scanner to my phone hotspot but each time I try to connect it again (I switched to my normal network previously) the password input popups and request the password, but that network is a known network, right? Why is it asking for the pass again? Is this the expected behavior?
> 
> Is it like this in prod? @bjdose

Yes, that's the production behavior

**Review by bjdose — APPROVED** [review]

**Pull request merged**
